<?php
/* vim: set expandtab tabstop=4 shiftwidth=4: */
// +----------------------------------------------------------------------+
// | Automne (TM)														  |
// +----------------------------------------------------------------------+
// | Copyright (c) 2000-2009 WS Interactive								  |
// +----------------------------------------------------------------------+
// | Automne is subject to version 2.0 or above of the GPL license.		  |
// | The license text is bundled with this package in the file			  |
// | LICENSE-GPL, and is available through the world-wide-web at		  |
// | http://www.gnu.org/copyleft/gpl.html.								  |
// +----------------------------------------------------------------------+
// | Author: Antoine Pouch <antoine.pouch@ws-interactive.fr> &            |
// | Author: Sébastien Pauchet <sebastien.pauchet@ws-interactive.fr>      |
// +----------------------------------------------------------------------+
//
// $Id: cms_rc.php,v 1.7 2009/03/04 09:54:51 sebastien Exp $

/**
  * rc file, contains editable constants
  * @author Antoine Pouch <antoine.pouch@ws-interactive.fr> &
  * @author Sébastien Pauchet <sebastien.pauchet@ws-interactive.fr> &
  * @author Cédric Soret <cedric.soret@ws-interactive.fr>
  */
//include general configuration file
if (@file_exists(dirname(__FILE__)."/config.php")) {
	@include_once(dirname(__FILE__)."/config.php");
} elseif(!isset($_SERVER['SCRIPT_NAME']) || $_SERVER['SCRIPT_NAME'] != '/install.php') {
	die('Cannot find config.php file, please run Automne installation again ...');
}

//check PHP version requirement
if (version_compare(phpversion(), "5.2.0", "<")) {
	die('Automne require PHP version 5.2.0 minimum. Your current version is : '.phpversion());
}

// ****************************************************************
// ** EDITABLE CONSTANT (add new values in config.php file)      **
// **             /!\ DO NOT EDIT THIS FILE /!\                  **
// ****************************************************************

/**
  *	Application default language
  *	Default : "fr"
  */
if (!defined("APPLICATION_DEFAULT_LANGUAGE")) {
	define("APPLICATION_DEFAULT_LANGUAGE", "fr");
}

/**
  *	Application default encoding
  * supported values are iso-8859-1 or utf-8
  *	Default : "iso-8859-1"
  */
if (!defined("APPLICATION_DEFAULT_ENCODING")) {
	define("APPLICATION_DEFAULT_ENCODING", "iso-8859-1");
}

/**
  *	Cookie expiration, in days.
  *	Default : 15 (days)
  */
if (!defined("APPLICATION_COOKIE_EXPIRATION")) {
	define("APPLICATION_COOKIE_EXPIRATION", 15);
}

/**
  *	Administration session timeout, in seconds.
  *	Default : 3600 (60 minutes)
  */
if (!defined("APPLICATION_SESSION_TIMEOUT")) {
	define("APPLICATION_SESSION_TIMEOUT", 3600);
}

/**
  *	Application error reporting level
  *	Default : E_ALL or E_ALL & ~E_NOTICE in old Automne version
  */
if (!defined("APPLICATION_ERROR_REPORTING")) {
	define("APPLICATION_ERROR_REPORTING", E_ALL);
}
/**
  *	Application memory limit level
  *	Default : 32M
  */
if (!defined("APPLICATION_MEMORY_LIMIT")) {
	define("APPLICATION_MEMORY_LIMIT", "32M");
}

/**
  *	Database host.
  *	Default : "localhost"
  */
if (!defined("APPLICATION_DB_HOST")) {
	define("APPLICATION_DB_HOST", "localhost");
}

/**
  *	Database name.
  *	Default : "automne4"
  */
if (!defined("APPLICATION_DB_NAME")) {
	define("APPLICATION_DB_NAME", "automne4");
}

/**
  *	Database user.
  *	Default : "automne"
  */
if (!defined("APPLICATION_DB_USER")) {
	define("APPLICATION_DB_USER", "automne");
}

/**
  *	Database password.
  *	Default : "automne"
  */
if (!defined("APPLICATION_DB_PASSWORD")) {
	define("APPLICATION_DB_PASSWORD", "automne");
}

/**
  *	Database dsn.
  * Default : "mysql:host=".APPLICATION_DB_HOST.";dbname=".APPLICATION_DB_NAME
  */
if (!defined("APPLICATION_DB_DSN")) {
	define("APPLICATION_DB_DSN", "mysql:host=".APPLICATION_DB_HOST.";dbname=".APPLICATION_DB_NAME);
}

/**
  *	Database persistent connection status.
  *	Default : false
  */
if (!defined("APPLICATION_DB_PERSISTENT_CONNNECTION")) {
	define("APPLICATION_DB_PERSISTENT_CONNNECTION", false);
}

/**
  *	Activate HTML Compression for Automne pages
  *	Default : true
  */
if (!defined("ENABLE_HTML_COMPRESSION")) {
	define("ENABLE_HTML_COMPRESSION", true);
}

/**
  *	XHTML DTD used in page generation.
  *	Default : XHTML 1.0 transitionnal : "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\t\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
  */
if (!defined("APPLICATION_XHTML_DTD")) {
	define("APPLICATION_XHTML_DTD", "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\t\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
}

/**
  *	Does system application run on Windows platform
  *	Default : strtolower(substr(PHP_OS, 0, 3)) === 'win'
  */
if (!defined("APPLICATION_IS_WINDOWS")) {
	define("APPLICATION_IS_WINDOWS", (strtolower(substr(PHP_OS, 0, 3)) === 'win'));
}

/**
  *	FrontEnd not found page URL (404)
  * wrong users privilège or session time out redirect to this page
  *	Default : /404.php
  */
if (!defined("PATH_SPECIAL_PAGE_NOT_FOUND_WR")) {
	define("PATH_SPECIAL_PAGE_NOT_FOUND_WR", '/404.php');
}

/**
  *	Path to the PHP CLI executable under windows
  *	Default : "c:\php\cli\php.exe"
  */
if (!defined("PATH_PHP_CLI_WINDOWS")) {
	define("PATH_PHP_CLI_WINDOWS", "c:\php\cli\php.exe");
}

/**
  *	Path to the PHP temp.
  * Required on Windows system.
  * Empty if session.save_path is useable on Unix system.
  * 
  *	Default : 'c:\tmp\\' (windows) or '\tmp' (unix) or $_SERVER["DOCUMENT_ROOT"]."/tmp"
  */
if (!defined("PATH_PHP_TMP")) {
	define("PATH_PHP_TMP", '');
}

/**
  * Defines files and directories permissions when written (used for PHP 
  * files, so check your security configuration) 
  *	Default : directory : 0775 and file : 0664
  */
if (!defined("FILES_CHMOD")) {
	define("FILES_CHMOD", "0664");
}
if (!defined("DIRS_CHMOD")) {
	define("DIRS_CHMOD", "0775");
}

/**
 * LDAP Authentication server address
 * For further options :
 * @see CMS_ldap_auth
 * @see CMS_ldap_query
 * 
 * Default : ldap://localhost
 */
if (!defined("APPLICATION_LDAP_SERVER")) {
	define("APPLICATION_LDAP_SERVER", "ldap://localhost");
}

/**
 * LDAP Server port
 * Default : 389
 */
if (!defined("APPLICATION_LDAP_PORT")) {
	define("APPLICATION_LDAP_PORT", 389);
}

/**
 * LDAP Server base DN
 * Default : dc=ws,o=automne
 */
if (!defined("APPLICATION_LDAP_BASE_DN")) {
	define("APPLICATION_LDAP_BASE_DN", "dc=ws,dc=automne");
}

/**
 * Default user to connect to server
 * Default : anonymous
 */
if (!defined("APPLICATION_LDAP_AUTH_USER")) {
	define("APPLICATION_LDAP_AUTH_USER", "cn=anonymous,dc=ws,dc=net");
}

/**
 * Default password to connect to server
 * Default : anonymous
 */
if (!defined("APPLICATION_LDAP_AUTH_PASSWORD")) {
	define("APPLICATION_LDAP_AUTH_PASSWORD", "anonymous");
}

/**
 * LDAP group user belong to
 * 
 * Represents the LDAP attribute determining the group user belongs to
 * It must be present in the LDAP directory for each user entry
 * Corresponds to a CMS_profile_usersGroup 'cn' part(s) of its 'dn'
 * attribute (the value of this attribute will be appened with
 * APPLICATION_LDAP_BASE_DN to get full group 'dn').
 * 
 * or represents the CMS_profile_usersGroup ID used by default 
 * for any new user entering for the first time in the application
 * 
 * Default : 1
 */
if (!defined('APPLICATION_LDAP_DEFAULT_GROUP')) {
	define('APPLICATION_LDAP_DEFAULT_GROUP', '1');
}

/**
  *	Application Main root page DB ID
  *	Default : 1
  */
if (!defined("APPLICATION_ROOT_PAGE_ID")) {
	define("APPLICATION_ROOT_PAGE_ID", 1);
}

/**
  *	Does application enforces workflow for the resources ?
  *	Default : true
  */
if (!defined("APPLICATION_ENFORCES_WORKFLOW")) {
	define("APPLICATION_ENFORCES_WORKFLOW", true);
}

/**
  * Define User Login if APPLICATION_ENFORCES_ACCESS_CONTROL is True (default login, need to be declared in admin profileuser)
  */
if (!defined("DEFAULT_USER_LOGIN")) {
	define("DEFAULT_USER_LOGIN", "anonymous");
}
/**
  * Define User Password if APPLICATION_ENFORCES_ACCESS_CONTROL is True (default password, need to be declared in admin profileuser)
  */
if (!defined("DEFAULT_USER_PASSWORD")) {
	define("DEFAULT_USER_PASSWORD", "anonymous");
}

/**
  * Define minimum user password length
  * Default : 5 caracters
  */
if (!defined("MINIMUM_PASSWORD_LENGTH")) {
	define("MINIMUM_PASSWORD_LENGTH", 5);
}

/**
  *	Main path where the CMS lies
  *	Default : "/cms"
  */
if (!defined("PATH_MAIN_WR")) {
	define("PATH_MAIN_WR", "/automne");
}

/**
  *	Path of the REAL document root
  *	Default : $_SERVER["DOCUMENT_ROOT"]
  */
if ($_SERVER["DOCUMENT_ROOT"] != dirname(__FILE__)) {
	//rewrite server document root if needed
	$_SERVER["DOCUMENT_ROOT"] = dirname(__FILE__);
}
//check we're not in a subdir
if (!is_dir($_SERVER["DOCUMENT_ROOT"].PATH_MAIN_WR)) {
	define("PATH_REALROOT_FS", substr($_SERVER["DOCUMENT_ROOT"], 0, strrpos($_SERVER["DOCUMENT_ROOT"], "html") - 1));
} else {
	define("PATH_REALROOT_FS", $_SERVER["DOCUMENT_ROOT"]);
}
if (!defined("PATH_MAIN_FS")) {
	define("PATH_MAIN_FS", PATH_REALROOT_FS.PATH_MAIN_WR);
}

/**
  *	Block files (files uploaded that represents blocks content)
  *	Default : DOCUMENT_ROOT."/cms_blocks_files"
  */
if (!defined("PATH_MODULES_FILES_WR")) {
	define("PATH_MODULES_FILES_WR", "/automne_modules_files");
}
if (!defined("PATH_MODULES_FILES_FS")) {
	define("PATH_MODULES_FILES_FS", PATH_REALROOT_FS."/automne_modules_files");
}
/**
  * PATH to the module files of the standard module
  */
if (!defined("PATH_MODULES_FILES_STANDARD_WR")) {
	define ('PATH_MODULES_FILES_STANDARD_WR', PATH_MODULES_FILES_WR."/standard");
}
if (!defined("PATH_MODULES_FILES_STANDARD_FS")) {
	define ('PATH_MODULES_FILES_STANDARD_FS', PATH_MODULES_FILES_FS."/standard");
}
/**
  *	Pages main root, where the pages from the main website will be located. 
  * Other websites are set to use subdirectories of this one.
  *	Default : PATH_MAIN_xx."/web"
  */
if (!defined("PATH_PAGES_WR")) {
	define("PATH_PAGES_WR", "/web");
}
if (!defined("PATH_PAGES_FS")) {
	define("PATH_PAGES_FS", PATH_REALROOT_FS."/web");
}

/**
  *	HTML Pages main root, where the html pages from the main website will be located. 
  * Other websites are set to use subdirectories of this one.
  *	Default : PATH_MAIN_xx."/html"
  */
if (!defined("PATH_PAGES_HTML_WR")) {
	define("PATH_PAGES_HTML_WR", "/html");
}
if (!defined("PATH_PAGES_HTML_FS")) {
	define("PATH_PAGES_HTML_FS", PATH_REALROOT_FS."/html");
}

/**
  *	Packages path (where are the declaration files of the core packages)
  *	Default : PATH_MAIN_xx."/classes"
  */
if (!defined("PATH_PACKAGES_WR")) {
	define("PATH_PACKAGES_WR", PATH_MAIN_WR."/classes");
}
if (!defined("PATH_PACKAGES_FS")) {
	define("PATH_PACKAGES_FS", PATH_MAIN_FS."/classes");
}

/**
  *	phpMyAdmin index path
  *	Default : PATH_MAIN_xx."/phpMyAdmin/index.php"
  */
if (!defined("PATH_PHPMYADMIN_WR")) {
	define("PATH_PHPMYADMIN_WR", PATH_MAIN_WR."/phpMyAdmin/index.php");
}
if (!defined("PATH_PHPMYADMIN_FS")) {
	define("PATH_PHPMYADMIN_FS", PATH_MAIN_FS."/phpMyAdmin/index.php");
}

/**
  *	Modules path (where are the declaration files of the modules)
  *	Default : PATH_MAIN_xx."/classes/modules"
  */
if (!defined("PATH_MODULES_WR")) {
	define("PATH_MODULES_WR", PATH_MAIN_WR."/classes/modules");
}
if (!defined("PATH_MODULES_FS")) {
	define("PATH_MODULES_FS", PATH_MAIN_FS."/classes/modules");
}

/**
  *	Templates path (where are the declaration files of the templates)
  *	Default : PATH_MAIN_xx."/templates"
  */
if (!defined("PATH_TEMPLATES_WR")) {
	define("PATH_TEMPLATES_WR", PATH_MAIN_WR."/templates");
}
if (!defined("PATH_TEMPLATES_FS")) {
	define("PATH_TEMPLATES_FS", PATH_MAIN_FS."/templates");
}

/**
  *	Templates rows definition files paths (where are the definition files of the rows)
  *	Default : PATH_MAIN_xx."/templates/rows"
  */
if (!defined("PATH_TEMPLATES_ROWS_WR")) {
	define("PATH_TEMPLATES_ROWS_WR", PATH_MAIN_WR."/templates/rows");
}
if (!defined("PATH_TEMPLATES_ROWS_FS")) {
	define("PATH_TEMPLATES_ROWS_FS", PATH_MAIN_FS."/templates/rows");
}

if (!defined("PATH_MAIL_TEMPLATES_FS")) {
	define("PATH_MAIL_TEMPLATES_FS", PATH_TEMPLATES_FS.'/mail/mail.xml');
}
if (!defined("PATH_PRINT_TEMPLATES_FS")) {
	define("PATH_PRINT_TEMPLATES_FS", PATH_TEMPLATES_FS.'/print.xml');
}

/**
  *	CSS file paths (where is css definition files)
  *	Default : DOCUMENT_ROOT."/css"
  */
if (!defined("PATH_CSS_WR")) {
	define("PATH_CSS_WR", "/css");
}
if (!defined("PATH_CSS_FS")) {
	define("PATH_CSS_FS", PATH_REALROOT_FS."/css");
}
/**
  *	JS file paths (where is js definition files)
  *	Default : DOCUMENT_ROOT."/js"
  */
if (!defined("PATH_JS_WR")) {
	define("PATH_JS_WR", "/js");
}
if (!defined("PATH_JS_FS")) {
	define("PATH_JS_FS", PATH_REALROOT_FS."/js");
}
/**
  *	Path where the pages originally lies
  *	Default : "/html"
  */
if (!defined("PATH_PAGES_WR")) {
	define("PATH_PAGES_WR",  "/html");
}
if (!defined("PATH_PAGES_FS")) {
	define("PATH_PAGES_FS",  PATH_REALROOT_FS."/html");
}
/**
  *	Path where the htaccess templates originally lies
  *	Default : PATH_TEMPLATES_FS."/htaccess"
  */
if (!defined("PATH_HTACCESS_FS")) {
	define("PATH_HTACCESS_FS",  PATH_TEMPLATES_FS."/htaccess");
}

/*
  *	Administration default language
  *	Default : fr (French)
  */
if (!defined("ADMINISTRATION_DEFAULT_LANGUAGE")) {
	define("ADMINISTRATION_DEFAULT_LANGUAGE", "fr");
}

/**
  *	Number of simultaneous sub_scripts for the regenerator
  *	Default : "2"
  *	Max : "10"
  */
if (!defined("REGENERATION_THREADS")) {
	define("REGENERATION_THREADS", "2");
}

/**
  *	Automne UPDATE.DENY File
  *	Default : PATH_MAIN_WR."/UPDATE.DENY"
  */
if (!defined("UPDATE_DENY")) {
	define("UPDATE_DENY", PATH_MAIN_WR."/UPDATE.DENY");
}

/**
  *	Administration path
  *	Default : PATH_MAIN_xx."/cms"
  */
if (!defined("PATH_ADMIN_WR")) {
	define("PATH_ADMIN_WR", PATH_MAIN_WR."/admin");
}
if (!defined("PATH_ADMIN_FS")) {
	define("PATH_ADMIN_FS", PATH_MAIN_FS."/admin");
}

/**
  * Modules administration path
  * Default : PATH_ADMIN_xx."/modules"
  */
if (!defined("PATH_ADMIN_MODULES_WR")) {
	define("PATH_ADMIN_MODULES_WR", PATH_ADMIN_WR."/modules");
}
if (!defined("PATH_ADMIN_MODULES_FS")) {
	define("PATH_ADMIN_MODULES_FS", PATH_ADMIN_FS."/modules");
}

/**
  *	Administration images path
  *	Default : PATH_ADMIN_xx."/img"
  */
if (!defined("PATH_ADMIN_IMAGES_WR")) {
	define("PATH_ADMIN_IMAGES_WR", PATH_ADMIN_WR."/img");
}
if (!defined("PATH_ADMIN_IMAGES_FS")) {
	define("PATH_ADMIN_IMAGES_FS", PATH_ADMIN_FS."/img");
}

/**
  *	Administration css path
  *	Default : PATH_ADMIN_xx."/css"
  */
if (!defined("PATH_ADMIN_CSS_WR")) {
	define("PATH_ADMIN_CSS_WR", PATH_ADMIN_WR."/css");
}
if (!defined("PATH_ADMIN_CSS_FS")) {
	define("PATH_ADMIN_CSS_FS", PATH_ADMIN_FS."/css");
}

/**
  *	Administration js path
  *	Default : PATH_ADMIN_xx."/js"
  */
if (!defined("PATH_ADMIN_JS_WR")) {
	define("PATH_ADMIN_JS_WR", PATH_ADMIN_WR."/js");
}
if (!defined("PATH_ADMIN_JS_FS")) {
	define("PATH_ADMIN_JS_FS", PATH_ADMIN_FS."/js");
}

/**
  *	Administration special pages paths : login page
  *	Default : PATH_ADMIN_xx."/index.php"
  */
if (!defined("PATH_ADMIN_SPECIAL_LOGIN_WR")) {
	define("PATH_ADMIN_SPECIAL_LOGIN_WR", PATH_ADMIN_WR."/index.php");
}

/**
  *	This constant was used before Automne V4 for admin session management purposes.
  * Now it is used to set some PHP vars for old V3 modules compatibility
  *	Default : PATH_ADMIN_xx."/compat-v3.php"
  */
if (!defined("PATH_ADMIN_SPECIAL_SESSION_CHECK_FS")) {
	define("PATH_ADMIN_SPECIAL_SESSION_CHECK_FS", PATH_ADMIN_FS."/compat-v3.php");
}

/**
  *	Administration special pages paths : page templates client spaces edition
  *	Default : PATH_ADMIN_xx."/template_clientSpaces.php"
  */
if (!defined("PATH_ADMIN_SPECIAL_SERVER_RESPONSE_WR")) {
	define("PATH_ADMIN_SPECIAL_SERVER_RESPONSE_WR", PATH_ADMIN_WR."/serverResponse.php");
}

/**
  *	Pages templates path
  *	Default : PATH_MAIN_xx."/templates"
  */
if (!defined("PATH_TEMPLATES_WR")) {
	define("PATH_TEMPLATES_WR", PATH_MAIN_WR."/templates");
}
if (!defined("PATH_TEMPLATES_FS")) {
	define("PATH_TEMPLATES_FS", PATH_MAIN_FS."/templates");
}

/**
  *	Temp path (where automne updates patch are uncompressed, files uploaded, etc.
  *	Default : PATH_MAIN_xx."/tmp"
  */
if (!defined("PATH_TMP_WR")) {
	define("PATH_TMP_WR", PATH_MAIN_WR."/tmp");
}
if (!defined("PATH_TMP_FS")) {
	define("PATH_TMP_FS", PATH_MAIN_FS."/tmp");
}

/**
  *	Pages templates rows definition files path
  *	Default : PATH_MAIN_xx."/templates/rows"
  */
if (!defined("PATH_ROWS_WR")) {
	define("PATH_ROWS_WR", PATH_MAIN_WR."/templates/rows");
}
if (!defined("PATH_ROWS_FS")) {
	define("PATH_ROWS_FS", PATH_MAIN_FS."/templates/rows");
}

/**
  *	Pages templates description images path
  *	Default : PATH_TEMPLATES_xx."/images"
  */
if (!defined("PATH_TEMPLATES_IMAGES_WR")) {
	define("PATH_TEMPLATES_IMAGES_WR", PATH_TEMPLATES_WR."/images");
}
if (!defined("PATH_TEMPLATES_IMAGES_FS")) {
	define("PATH_TEMPLATES_IMAGES_FS", PATH_TEMPLATES_FS."/images");
}

/**
  * Pages linx files path, where the linx files are located. 
  * Other websites are set to use subdirectories of this one.
  *	Default : PATH_MAIN_xx."/automne_linx_files"
  */
if (!defined("PATH_PAGES_LINXFILES_WR")) {
	define("PATH_PAGES_LINXFILES_WR", "/automne_linx_files");
}
if (!defined("PATH_PAGES_LINXFILES_FS")) {
	define("PATH_PAGES_LINXFILES_FS", PATH_REALROOT_FS."/automne_linx_files");
}

/**
  * Windows Binary and bat files path, where usefull windows files are located. 
  *	Default : PATH_REALROOT_xx."/automne_bin"
  */
if (!defined("PATH_WINDOWS_BIN_WR")) {
	define("PATH_WINDOWS_BIN_WR", "/automne_bin");
}
if (!defined("PATH_WINDOWS_BIN_FS")) {
	define("PATH_WINDOWS_BIN_FS", PATH_REALROOT_FS."/automne_bin");
}

/**
  *	Automne general chmod configuration file
  *	Default : PATH_PACKAGES_WR."/scripts/automneChmod"
  */
if (!defined("PATH_AUTOMNE_CHMOD_SCRIPT_FS")) {
	define("PATH_AUTOMNE_CHMOD_SCRIPT_FS", PATH_PACKAGES_FS."/files/htaccess.txt");
}
/**
  *	Automne mime types file
  *	Default : PATH_PACKAGES_FS."/files/mime.types"
  */
if (!defined("PATH_AUTOMNE_MIMETYPE_FS")) {
	define("PATH_AUTOMNE_MIMETYPE_FS", PATH_PACKAGES_FS."/files/mime.types");
}

/**
  * Special profile users ID
  */
if (!defined("ROOT_PROFILEUSER_ID")) {
	define("ROOT_PROFILEUSER_ID", 1);
}
if (!defined("ANONYMOUS_PROFILEUSER_ID")) {
	define("ANONYMOUS_PROFILEUSER_ID", 3);
}

if (!defined("CHECK_REMOTE_IP_MASK")) {
    define("CHECK_REMOTE_IP_MASK", true);
}

/**
  * LDAP constants
  */
if (!defined('APPLICATION_LDAP_USER_DN')) {
	define('APPLICATION_LDAP_USER_DN', 'dn');
}
if (!defined('APPLICATION_LDAP_USER_LOGIN')) {
	define('APPLICATION_LDAP_USER_LOGIN', 'uid');
}
if (!defined('APPLICATION_LDAP_USER_PASSWORD')) {
	define('APPLICATION_LDAP_USER_PASSWORD', 'userpassword');
}
if (!defined('APPLICATION_LDAP_USER_FIRSTNAME')) {
	define('APPLICATION_LDAP_USER_FIRSTNAME', 'givenname');
}
if (!defined('APPLICATION_LDAP_USER_LASTNAME')) {
	define('APPLICATION_LDAP_USER_LASTNAME', 'cn');
}
if (!defined('APPLICATION_LDAP_USER_EMAIL')) {
	define('APPLICATION_LDAP_USER_EMAIL', 'mail');
}
if (!defined('APPLICATION_LDAP_USER_JOBTITLE')) {
	define('APPLICATION_LDAP_USER_JOBTITLE', '');
}
if (!defined('APPLICATION_LDAP_USER_FAX')) {
	define('APPLICATION_LDAP_USER_FAX', '');
}
if (!defined('APPLICATION_LDAP_USER_PHONE')) {
	define('APPLICATION_LDAP_USER_PHONE', '');
}
if (!defined('APPLICATION_LDAP_USER_CELLPHONE')) {
	define('APPLICATION_LDAP_USER_CELLPHONE', '');
}
if (!defined('APPLICATION_LDAP_USER_SERVICE')) {
	define('APPLICATION_LDAP_USER_SERVICE', '');
}
if (!defined('APPLICATION_LDAP_USER_ADDRESS1')) {
	define('APPLICATION_LDAP_USER_ADDRESS1', '');
}
if (!defined('APPLICATION_LDAP_USER_ADDRESS2')) {
	define('APPLICATION_LDAP_USER_ADDRESS2', '');
}
if (!defined('APPLICATION_LDAP_USER_ADDRESS3')) {
	define('APPLICATION_LDAP_USER_ADDRESS3', '');
}
if (!defined('APPLICATION_LDAP_USER_CITY')) {
	define('APPLICATION_LDAP_USER_CITY', '');
}
if (!defined('APPLICATION_LDAP_USER_ZIPCODE')) {
	define('APPLICATION_LDAP_USER_ZIPCODE', '');
}
if (!defined('APPLICATION_LDAP_USER_COUNTRY')) {
	define('APPLICATION_LDAP_USER_COUNTRY', '');
}
if (!defined('APPLICATION_LDAP_USER_REGIONSTATE')) {
	define('APPLICATION_LDAP_USER_REGIONSTATE', '');
}

/**
  *	Files extensions denied for upload, comma separated
  *	Default : 'exe,php,pif,vbs,bat,com,scr,reg'
  */
if (!defined('FILE_UPLOAD_EXTENSIONS_DENIED')) {
	define('FILE_UPLOAD_EXTENSIONS_DENIED', 'exe,php,pif,vbs,bat,com,scr,reg');
}

// ****************************************************************
// ** CONSTANTS ARE NOT EDITABLE BEYOND THIS POINT               **
// ****************************************************************

/**
  * Define execution Type
  */
if (!defined("APPLICATION_EXEC_TYPE")) {
	define("APPLICATION_EXEC_TYPE", "http");
}

//augment memory_limit
if (ini_get('memory_limit') < (int) APPLICATION_MEMORY_LIMIT) {
	@ini_set('memory_limit', APPLICATION_MEMORY_LIMIT);
}
//try to remove magic quotes
@ini_set('magic_quotes_gpc', 0);
@ini_set('magic_quotes_runtime', 0);
@ini_set('magic_quotes_sybase', 0);
//try to change some misconfigurations
@ini_set('session.gc_probability', 0);
@ini_set('allow_call_time_pass_reference', 0);

//remove NOTICE to avoid useless notice messages.
error_reporting(APPLICATION_ERROR_REPORTING);

//load standard config file parameters (PATH_MODULES_FS.'/standard_rc.xml')
require_once(PATH_PACKAGES_FS."/modules/readStandardParam.php");
//set default level of output compression (if any)
@ini_set('zlib.output_compression_level',6);

/**
  *	Automne version number
  */
if (!defined("AUTOMNE_VERSION") && file_exists(PATH_REALROOT_FS."/VERSION")) {
	define("AUTOMNE_VERSION", file_get_contents(PATH_REALROOT_FS."/VERSION"));
} else if(!defined("AUTOMNE_VERSION") && !file_exists(PATH_REALROOT_FS."/VERSION")) {
	define("AUTOMNE_VERSION", 'Unknown');
}
/**
  *	Automne subversion number. Used to avoid JS and CSS browser cache
  */
if (!defined("AUTOMNE_SUBVERSION")) {
	define("AUTOMNE_SUBVERSION", 0);
}

if (STATS_DEBUG) {
	function view_stat($return = false){ 
		$time_end = getmicrotime();
		$time = sprintf('%.5f', $time_end - $GLOBALS["time_start"]);
		$files = sprintf('%.5f', $GLOBALS["files_time"]);
		$rapportSQL = sprintf('%.2f', ((100*$GLOBALS["total_time"])/$time));
		$rapportPHP = 100-$rapportSQL;
		$content = 
		'File ' .$_SERVER['SCRIPT_NAME'] ."\n".
		'Loaded in ' . $time . ' seconds'."\n".
		'Loaded PHP files : '. $GLOBALS["files_loaded"] ."\n".
		'SQL requests : ' . sprintf('%.5f',$GLOBALS["total_time"]) . ' seconds ('. $GLOBALS["sql_nb_requests"] .' requests)'."\n".
		'% SQL/PHP : '. $rapportSQL .' / '. $rapportPHP .' %'."\n";
		if (function_exists('xdebug_get_profiler_filename') && xdebug_get_profiler_filename()) {
			$content .= 'XDebug Profile : '. xdebug_get_profiler_filename()."\n";
		}
		if (function_exists('xdebug_get_profiler_filename') && xdebug_get_tracefile_name()) {
			$content .= 'XDebug Trace : '. xdebug_get_tracefile_name()."\n";
		}
		if (VIEW_SQL && isset($_SESSION["cms_context"]) && is_object($_SESSION["cms_context"]) && $_SERVER["SCRIPT_NAME"]!="/automne/admin/stat.php") {
			$stats = $_SESSION["cms_context"]->getSessionVar('automneStats');
			if (!$stats) {
				$stats = array();
			}
			//limit to last 4 stats
			if (sizeof($stats) >= 4) {
				$stats = array_slice($stats, sizeof($stats) - 3);
			}
			$stat = array(
				'stat_time_start'		=> $GLOBALS["time_start"],
				'stat_time_end'			=> getmicrotime(),
				'stat_total_time'		=> $GLOBALS["total_time"],
				'stat_sql_nb_requests'	=> $GLOBALS["sql_nb_requests"],
				'stat_sql_table'		=> $GLOBALS["sql_table"],
				'stat_content_name'		=> basename($_SERVER["SCRIPT_NAME"]),
				'stat_files_table'		=> $GLOBALS["files_table"],
				'stat_files_loaded'		=> $GLOBALS["files_loaded"],
			);
			$statName = 'stat-'.md5(rand());
			$stats[$statName] = $stat;
			$_SESSION["cms_context"]->setSessionVar('automneStats', $stats);
		}
		if (!$return) {
			$content = '<pre>'.$content.'</pre>';
			if (isset($statName)) {
				$content .= '<a href="/automne/admin/stat.php?stat='.$statName.'" target="_blank">View statistics</a>';
			}
			echo $content;
		} else {
			if (isset($statName)) {
				$content .= '<a href="/automne/admin/stat.php?stat='.$statName.'" target="_blank">View statistics</a>';
			}
			return $content;
		}
	}
	$GLOBALS["sql_nb_requests"] = $GLOBALS["total_time"] = $GLOBALS["files_time"] = 0;
	$GLOBALS["files_loaded"] = 4; //Start at 4 : 3 config files and the require at the end of this file
	$GLOBALS["time_start"] = getmicrotime();
}

//include base packages
require_once(PATH_PACKAGES_FS."/common/grandfather.php");

/**
  * Debug mode configuration changes.
  */
if (SYSTEM_DEBUG) {
	//Display errors in Debug Mode
	if (function_exists("ini_set")) {
		@ini_set("display_errors", "1");
		@ini_set('output_buffering','Off');
	}
	//Usefull function to dump a var.
	function pr($data,$useVarDump = false)
	{
		$view = CMS_view::getInstance();
		if (!$useVarDump) {
			//echo "<pre>".print_r($data,true)."</pre>";
			$view->addRawData(print_r($data,true));
			//flush();
		} else {
			//echo "<pre>";
			ob_start();
			var_dump($data);
			$rawdata = ob_get_contents();
			ob_end_clean();
			$view->addRawData($rawdata);
			//echo "</pre>";
			//flush();
		}
	}
} else {
	//Remove all errors in Production.
	//Errors are logged in cms_error_log file
	if (function_exists("ini_set")) {
		@ini_set("display_errors", "0");
		@ini_set('output_buffering','On');
	} elseif(function_exists("error_reporting")) {
		error_reporting(0);
	}
	//Usefull function to dump a var.
	function pr($data,$useVarDump = false){}
}

/**
  * Usefull time function for statistics and regenerator
  */
function getmicrotime(){ 
	list($usec, $sec) = explode(" ",microtime()); 
	return ((float)$usec + (float)$sec); 
}

/**
  * If magic quotes is active, rewrite all super globals
  */
if (get_magic_quotes_gpc()) {
	// Strip slashes in content 
	function CMS_stripslashes($value) {
		$value = is_array($value) ? array_map('CMS_stripslashes', $value) : stripslashes($value) ;
		return $value;
	}
	$_POST = array_map('CMS_stripslashes', $_POST);
	$_GET = array_map('CMS_stripslashes', $_GET);
	$_COOKIE = array_map('CMS_stripslashes', $_COOKIE);
	$_REQUEST = array_map('CMS_stripslashes', $_REQUEST);
}

/**
  * If application APPLICATION_DEFAULT_ENCODING is not UTF-8, we need to decode all ajax requests
  */
if (isset($_SERVER['HTTP_X_REQUESTED_WITH'])
	&& strtolower(APPLICATION_DEFAULT_ENCODING) != 'utf-8' 
	&& $_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest') {
	function utf8_decode_callback (&$input, $index = '') {
		if (is_string($input)) {
			//to preserve the euro sign
			$input = strtr($input, array("\xe2\x82\xac" => "\xc2\x80"));
			//then decode UTF-8 content
			$input = utf8_decode($input);
			return $input;
		} elseif (is_array($input)) {
			array_walk_recursive($input, 'utf8_decode_callback');
			return $input;
		}
		return $input;
	}
	$_POST = array_map('utf8_decode_callback', $_POST);
	$_GET = array_map('utf8_decode_callback', $_GET);
	$_COOKIE = array_map('utf8_decode_callback', $_COOKIE);
	$_REQUEST = array_map('utf8_decode_callback', $_REQUEST);
}

/**
  * Check if output compression is enabled
  */
function compress_is_enabled() {
	return ( ENABLE_HTML_COMPRESSION
			 && 'ob_gzhandler' != ini_get('output_handler')
			 && extension_loaded( 'zlib' )
			 && !ini_get('zlib.output_compression')
			);
}

/**
  * Launch output compression if enabled
  */
function compress_handler( $p_buffer, $p_mode ) {
	if ( compress_is_enabled() ) {
		return ob_gzhandler( $p_buffer, $p_mode );
	} else {
		return $p_buffer;
	}
}

function start_atm_session() {
	// verify if PHP supports session, die if it does not
	if (!@function_exists('session_name')) {
	    die('Session is not available');
	} elseif (ini_get('session.auto_start') == true && session_name() != 'AutomneSession') {
	    // Do not delete the existing session, it might be used by other 
	    // applications; instead just close it.
	    session_write_close();
	}
	// session cookie settings
	session_set_cookie_params(0, '/', '', false);
	
	// cookies are safer (use @ini_set() in case this function is disabled)
	@ini_set('session.use_cookies', true);
	
	// but not all user allow cookies
	@ini_set('session.use_only_cookies', false);
	@ini_set('session.use_trans_sid', true);
	// delete session/cookies when browser is closed
	@ini_set('session.cookie_lifetime', 0);
	
	// warn but dont work with bug
	@ini_set('session.bug_compat_42', false);
	@ini_set('session.bug_compat_warn', true);
	
	// use more secure session ids
	@ini_set('session.hash_function', 1);
	
	// some pages (e.g. stylesheet) may be cached on clients, but not in shared
	// proxy servers
	session_cache_limiter('private');
	
	$session_name = 'AutomneSession';
	@session_name($session_name);
	
	@session_start();
}

define("MODULE_TREATMENT_PAGECONTENT_HEADER_CODE", 1);
define("MODULE_TREATMENT_PAGECONTENT_FOOTER_CODE", 2);
define("MODULE_TREATMENT_EDITOR_CODE", 4);
define("MODULE_TREATMENT_EDITOR_JSCODE", 8);
define("MODULE_TREATMENT_ROWS_EDITION_LABELS", 16);
define("MODULE_TREATMENT_TEMPLATES_EDITION_LABELS", 32);
define("MODULE_TREATMENT_BEFORE_VALIDATION_TREATMENT", 64);
define("MODULE_TREATMENT_AFTER_VALIDATION_TREATMENT", 128);
define("MODULE_TREATMENT_EDITOR_PLUGINS", 256);
define("MODULE_TREATMENT_ALERTS", 512);

define("MODULE_TREATMENT_PAGECONTENT_TAGS", 1);
define("MODULE_TREATMENT_CLIENTSPACE_TAGS", 2);
define("MODULE_TREATMENT_BLOCK_TAGS", 4);
define("MODULE_TREATMENT_LINXES_TAGS", 8);
define("MODULE_TREATMENT_WYSIWYG_INNER_TAGS", 16);
define("MODULE_TREATMENT_WYSIWYG_OUTER_TAGS", 32);

/**
  *	Paths are either relative to Filesystem root or Webroot
  *	Default : "WR" and "FS"
  */
define("PATH_RELATIVETO_WEBROOT", 1);
define("PATH_RELATIVETO_FILESYSTEM", 2);
/**
  * Resource locations. 
  * 	Userspace : resource can be used (edited, seen) by users
  * 	Archived : resource in in archive tables. Can't be seen by users except for administrators that can restore it.
  * 	Deleted : Resource is in deletion tables. Can't be seen by nobody.
  * 	Edition : resource is currently edited. Only valid for pages, and not reported in the array of available locations
  */
define("RESOURCE_LOCATION_USERSPACE", 1);
define("RESOURCE_LOCATION_ARCHIVED", 2);
define("RESOURCE_LOCATION_DELETED", 3);
define("RESOURCE_LOCATION_EDITION", 4);
/**
  * Resource possible editions. Multiple editions are added and stored in one variable.
  * 	Basedata : the base data of the resource was edited.
  * 	Content : the content of the resource was edited.
  * 	Siblingsorder : the siblings order was rearranged.
  * 	location : The proposedFor location was set
  */
define("RESOURCE_EDITION_BASEDATA", 1);
define("RESOURCE_EDITION_CONTENT", 2);
define("RESOURCE_EDITION_SIBLINGSORDER", 4);
define("RESOURCE_EDITION_LOCATION", 8);
define("RESOURCE_EDITION_MOVE", 16);
/**
  * Resource publications statuses.
  * 	Nevervalidated : the page was created and no validator moved it into public space.
  * 	validated : It has been already validated, but is not currently into its "window" of publication" defined by its publication dates.	
  * 	Public : It has been validated and is currently visible by the public
  */
define("RESOURCE_PUBLICATION_NEVERVALIDATED", 0);
define("RESOURCE_PUBLICATION_VALIDATED", 1);
define("RESOURCE_PUBLICATION_PUBLIC", 2);
/**
  * Resource data location : edited, edition, public, archived, deleted and "/dev/null", the infamous black hole
  */
define("RESOURCE_DATA_LOCATION_EDITED", "edited");
define("RESOURCE_DATA_LOCATION_EDITION", "edition");
define("RESOURCE_DATA_LOCATION_PUBLIC", "public");
define("RESOURCE_DATA_LOCATION_ARCHIVED", "archived");
define("RESOURCE_DATA_LOCATION_DELETED", "deleted");
define("RESOURCE_DATA_LOCATION_DEVNULL", "/dev/null");
/**
  * Link types : internal, external or none. Useful for module resources making links to pages or external websites
  */
define("RESOURCE_LINK_TYPE_NONE", 0);
define("RESOURCE_LINK_TYPE_INTERNAL", 1);
define("RESOURCE_LINK_TYPE_EXTERNAL", 2);
define("RESOURCE_LINK_TYPE_FILE", 3);
/**
* Clearance Modules permission levels
* Default : 0
*/
define("CLEARANCE_MODULE_NONE", 0);
define("CLEARANCE_MODULE_VIEW", 1);
define("CLEARANCE_MODULE_EDIT", 2);
define("CLEARANCE_MODULE_MANAGE", 3);
/**
* Clearance Pages permission levels
*/
define("CLEARANCE_PAGE_NONE", 0);
define("CLEARANCE_PAGE_VIEW", 1);
define("CLEARANCE_PAGE_EDIT", 2);
/**
* Clearance Administration permission levels
*/
define("CLEARANCE_ADMINISTRATION_EDITVALIDATEALL", 1);
define("CLEARANCE_ADMINISTRATION_REGENERATEPAGES", 2);
define("CLEARANCE_ADMINISTRATION_TEMPLATES", 4);
define("CLEARANCE_ADMINISTRATION_EDIT_TEMPLATES", 8);
define("CLEARANCE_ADMINISTRATION_VIEWLOG", 16);
define("CLEARANCE_ADMINISTRATION_EDITUSERS", 32);
define("CLEARANCE_ADMINISTRATION_VIEWCALENDAR", 64);
define("CLEARANCE_ADMINISTRATION_STATS", 128);
define("CLEARANCE_ADMINISTRATION_DUPLICATE_BRANCH", 256);
/**
* Alert Levels
*/
define("ALERT_LEVEL_VALIDATION", 1);
define("ALERT_LEVEL_PROFILE", 2);
define("ALERT_LEVEL_PAGE_ALERTS", 4);
/**
  * Validation option constants : ACCEPT, REFUSE and TRANSFER
  */
define("VALIDATION_OPTION_ACCEPT", 1);
define("VALIDATION_OPTION_REFUSE", 2);
define("VALIDATION_OPTION_TRANSFER", 4);
?>