ALTER TABLE `sessions` DROP INDEX `id_ses`;
ALTER TABLE `sessions` ADD INDEX ( `phpid_ses` );
ALTER TABLE `sessions` ADD INDEX ( `user_ses` );
ALTER TABLE `sessions` ADD INDEX ( `cookie_expire_ses` );
ALTER TABLE `locks` DROP INDEX `id_lok`;
ALTER TABLE `locks` ADD INDEX ( `resource_lok` );
ALTER TABLE `pageTemplates` DROP INDEX `id_pt`; 
ALTER TABLE `regenerator` DROP INDEX `page_reg`;
ALTER TABLE `contactDatas` DROP INDEX `id_cd`;
ALTER TABLE `I18NM_messages` ADD INDEX ( `module` );
ALTER TABLE `languages` DROP INDEX `code_lng`;
ALTER TABLE `linx_tree_public` DROP INDEX `id_ltr`;
ALTER TABLE `log` DROP INDEX `id_ulo`;
ALTER TABLE `modules` DROP INDEX `id_mod`;
ALTER TABLE `mod_standard_rows` DROP INDEX `id_row`;
ALTER TABLE `pages` DROP INDEX `id_pag`;
ALTER TABLE `pagesBaseData_archived` DROP INDEX `id_pbd`;
ALTER TABLE `pagesBaseData_deleted` DROP INDEX `id_pbd`;
ALTER TABLE `pagesBaseData_edited` DROP INDEX `id_pbd`;
ALTER TABLE `pagesBaseData_public` DROP INDEX `id_pbd`;
ALTER TABLE `profiles` DROP INDEX `id_pr`;
ALTER TABLE `profilesUsers` DROP INDEX `id_pru`;
ALTER TABLE `profilesUsersGroups` DROP INDEX `id_prg`;
ALTER TABLE `profilesUsers_validators` DROP INDEX `id_puv`;
ALTER TABLE `resources` DROP INDEX `id_res`;
ALTER TABLE `resourceStatuses` DROP INDEX `id_rs`;
ALTER TABLE `resourceValidations` DROP INDEX `id_rv`;
ALTER TABLE `websites` DROP INDEX `id_web`;
delete FROM `profileUsersByGroup` WHERE `userId_gu`='1';