<?php //Generated on Tue, 23 Jun 2009 18:04:54 +0200 by Automne (TM) 4.0.0rc1
if (!isset($cms_page_included) && !$_POST && !$_GET) {
	header('HTTP/1.x 301 Moved Permanently', true, 301);
	header('Location: http://127.0.0.1/web/fr/2-accueil.php');
	exit;
}
require_once($_SERVER["DOCUMENT_ROOT"]."/cms_rc_frontend.php");
 ?>
<?php require_once($_SERVER["DOCUMENT_ROOT"].'/automne/classes/polymodFrontEnd.php');  ?><?php if (defined('APPLICATION_XHTML_DTD')) echo APPLICATION_XHTML_DTD."\n";  ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Automne 4 : Automne version 4, goûter à la simplicité</title>
	<?php echo CMS_view::getCSS(array('/css/common.css','/css/accueil.css'), 'screen');  ?>

	<!--[if lte IE 6]> 
		<link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" />
	<![endif]-->
	<?php echo CMS_view::getJavascript(array('/js/sifr.js','/js/common.js','/js/CMS_functions.js','/js/modules/pnews/jquery-1.2.6.min.js','/js/modules/pnews/pnews.js'));  ?>

	<link rel="icon" type="image/x-icon" href="http://127.0.0.1/favicon.ico" />
	<meta name="description" content="Automne est un gestionnaire de contenu pour les entreprises open-source. Entièrement modulable il s'adpate à vos besoins." />
	<meta name="keywords" content="automne, cms, ecm, gestionnaire de contenu, toulouse, ws-interactive" />
	<meta name="language" content="fr" />
	<meta name="generator" content="Automne (TM)" />
	<meta name="identifier-url" content="http://127.0.0.1" />

	<!-- load the style of pnews module for media all -->
	<link rel="stylesheet" type="text/css" href="/css/modules/pnews.css" media="all" />

</head>
<body>
	<div id="main">
		<div id="container">
			<div id="header"></div>
			<h1>Automne version 4, goûter à la simplicité</h1>
			<div id="menuLeft">
				<div id="menuLeftBottom">
					<ul class="CMS_lvl2">
						<li class="CMS_lvl2"><a class="CMS_lvl2" href="http://127.0.0.1/web/fr/3-presentation.php">Présentation</a></li>
<li class="CMS_lvl2"><a class="CMS_lvl2" href="http://127.0.0.1/web/fr/24-documentation.php">Fonctionnalités</a></li>
<li class="CMS_lvl2"><a class="CMS_lvl2" href="http://127.0.0.1/web/fr/31-exemples-de-modules.php">Exemples de modules</a></li>
					</ul>
				</div>
			</div>
			<div id="content">
				<div id="firstCol">
					

<h2>Faciliter la communication et les échanges !</h2>



<div class="text"><p><strong>Automne est votre solution</strong> si vous recherchez un outil de gestion de contenu performant et &eacute;volutif. </p><p>Un outil permettant autonomie et contr&ocirc;le &eacute;ditorial.</p><p>Que votre contenu soit statique ou dynamique avec une gestion en bases de donn&eacute;es, Automne facilite la communication et les &eacute;changes <strong>sans contraintes techniques.<br /></strong></p></div>


				</div>
				<div id="secondCol">
					
	<?php //Generated by : $Id: 2.php,v 1.7 2009/06/23 16:00:40 sebastien Exp $
$content = "";
$replace = "";
if (!isset($objectDefinitions) || !is_array($objectDefinitions)) $objectDefinitions = array();
$blockAttributes = array (
	'module' => 'pnews',
	'language' => 'fr',
);
$parameters['pageID'] = '2';
if (!isset($cms_language) || (isset($cms_language) && $cms_language->getCode() != 'fr')) $cms_language = new CMS_language('fr');
$parameters['public'] = true;
if (isset($parameters['item'])) {$parameters['objectID'] = $parameters['item']->getObjectID();} elseif (isset($parameters['itemID']) && sensitiveIO::isPositiveInteger($parameters['itemID']) && !isset($parameters['objectID'])) $parameters['objectID'] = CMS_poly_object_catalog::getObjectDefinitionByID($parameters['itemID']);
if (!isset($object) || !is_array($object)) $object = array();
if (!isset($object[1])) $object[1] = new CMS_poly_object(1, 0, array(), $parameters['public']);
$parameters['module'] = 'pnews';
//SEARCH lastNews TAG START 2_76542b
$objectDefinition_lastNews = '1';
if (!isset($objectDefinitions[$objectDefinition_lastNews])) {
	$objectDefinitions[$objectDefinition_lastNews] = new CMS_poly_object_definition($objectDefinition_lastNews);
}
//public search ?
$public_2_76542b = isset($public_search) ? $public_search : false;
//get search params
$search_lastNews = new CMS_object_search($objectDefinitions[$objectDefinition_lastNews], $public_2_76542b);
$launchSearch_lastNews = true;
//add search conditions if any
$search_lastNews->setAttribute('itemsPerPage', (int) CMS_polymod_definition_parsing::replaceVars("1", $replace));
$search_lastNews->addOrderCondition("publication date after", "desc");
//RESULT lastNews TAG START 3_45fdbe
//launch search lastNews if not already done
if($launchSearch_lastNews && !isset($results_lastNews)) {
	if (isset($search_lastNews)) {
		$results_lastNews = $search_lastNews->search();
	} else {
		CMS_grandFather::raiseError("Malformed atm-result tag : can't use this tag outside of atm-search \"lastNews\" tag ...");
		$results_lastNews = array();
	}
} elseif (!$launchSearch_lastNews) {
	$results_lastNews = array();
}
if ($results_lastNews) {
	$object_3_45fdbe = $object[$objectDefinition_lastNews]; //save previous object search if any
	$replace_3_45fdbe = $replace; //save previous replace vars if any
	$count_3_45fdbe = 0;
	$content_3_45fdbe = $content; //save previous content var if any
	$maxPages_3_45fdbe = $search_lastNews->getMaxPages();
	$maxResults_3_45fdbe = $search_lastNews->getNumRows();
	foreach ($results_lastNews as $object[$objectDefinition_lastNews]) {
		$content = "";
		$replace["atm-search"] = array (
			"{resultid}" 	=> (isset($resultID_lastNews)) ? $resultID_lastNews : $object[$objectDefinition_lastNews]->getID(),
			"{firstresult}" => (!$count_3_45fdbe) ? 1 : 0,
			"{lastresult}" 	=> ($count_3_45fdbe == sizeof($results_lastNews)-1) ? 1 : 0,
			"{resultcount}" => ($count_3_45fdbe+1),
			"{maxpages}"    => $maxPages_3_45fdbe,
			"{currentpage}" => ($search_lastNews->getAttribute('page')+1),
			"{maxresults}"  => $maxResults_3_45fdbe,
		);
		$content .="
		<div class=\"lastNews\">
		<div class=\"newsTop\">
		<h3><a href=\"".CMS_tree::getPageValue("5","url")."?item=".$object[1]->getValue('id','')."\">".$object[1]->objectValues(1)->getValue('value','')."</a></h3>
		<span>".$object[1]->getValue('formatedDateStart','d/m/Y')."</span>
		<div class=\"spacer\"></div>
		</div>
		<div class=\"newsContent\">
		";
		//IF TAG START 4_188186
		$ifcondition = CMS_polymod_definition_parsing::replaceVars(CMS_polymod_definition_parsing::prepareVar($object[1]->objectValues(4)->getValue('imageWidth','')), $replace);
		if ($ifcondition) {
			$func = create_function("","return (".$ifcondition.");");
			if ($func()) {
				$content .="
				<div class=\"imgRight shadowR\">
				<div class=\"shadowB\">
				<div class=\"shadowTR\">
				<div class=\"shadowBL\">
				<div class=\"shadowBR\">
				<img src=\"".$object[1]->objectValues(4)->getValue('imagePath','')."/".$object[1]->objectValues(4)->getValue('imageName','')."\" alt=\"".$object[1]->objectValues(4)->getValue('imageLabel','')."\" title=\"".$object[1]->objectValues(4)->getValue('imageLabel','')."\" />
				</div>
				</div>
				</div>
				</div>
				</div>
				";
			}
		}//IF TAG END 4_188186
		$content .="
		".$object[1]->objectValues(2)->getValue('htmlvalue','')."
		";
		//IF TAG START 5_65d42a
		$ifcondition = CMS_polymod_definition_parsing::replaceVars(CMS_polymod_definition_parsing::prepareVar($object[1]->objectValues(3)->getValue('value','')), $replace);
		if ($ifcondition) {
			$func = create_function("","return (".$ifcondition.");");
			if ($func()) {
				$content .="
				<a href=\"".CMS_tree::getPageValue("5","url")."?item=".$object[1]->getValue('id','')."\" class=\"blocLien\" title=\"En savoir plus concernant '".$object[1]->getValue('label','')."'\">
				<span class=\"blocLienBottom\">En savoir plus</span>
				</a>
				";
			}
		}//IF TAG END 5_65d42a
		$content .="
		<div class=\"spacer\"></div>
		<div class=\"newsBottom\">
		<a class=\"newsAll\" href=\"".CMS_tree::getPageValue("5","url")."\">Toute l'actualite</a>
		";
		//FUNCTION TAG START 6_4e1119
		$parameters_6_4e1119 = array ('selected' => CMS_polymod_definition_parsing::replaceVars("3", $replace),);
		$object_6_4e1119 = &$object[1];
		if (method_exists($object_6_4e1119, "rss")) {
			$content .= CMS_polymod_definition_parsing::replaceVars($object_6_4e1119->rss($parameters_6_4e1119, array (
				0 =>
				array (
					'textnode' => '
					',
				),
				1 =>
				array (
					'nodename' => 'a',
					'attributes' =>
					array (
						'class' => 'newsRSS',
						'title' => '{description}',
						'href' => '{url}',
					),
					'childrens' =>
					array (
						0 =>
						array (
							'nodename' => 'img',
							'attributes' =>
							array (
								'src' => '/img/common/rss.gif',
								'alt' => '{label}',
							),
						),
					),
				),
				2 =>
				array (
					'textnode' => '
					',
				),
			)), $replace);
		} else {
			CMS_grandFather::raiseError("Malformed atm-function tag : can't found method rss on object : ".get_class($object_6_4e1119));
		}
		//FUNCTION TAG END 6_4e1119
		$content .="
		</div>
		</div>
		</div>
		";
		$count_3_45fdbe++;
		//do all result vars replacement
		$content_3_45fdbe.= CMS_polymod_definition_parsing::replaceVars($content, $replace);
	}
	$content = $content_3_45fdbe; //retrieve previous content var if any
	$replace = $replace_3_45fdbe; //retrieve previous replace vars if any
	$object[$objectDefinition_lastNews] = $object_3_45fdbe; //retrieve previous object search if any
}
//RESULT lastNews TAG END 3_45fdbe
//destroy search and results lastNews objects
unset($search_lastNews);
unset($results_lastNews);
//SEARCH lastNews TAG END 2_76542b
echo CMS_polymod_definition_parsing::replaceVars($content, $replace);
  ?>

				</div>
			</div>
			<div class="spacer"></div>
		</div>
	</div>
	<div id="footer">
		<div id="menuBottom">
			<ul>
				<li><a href="http://127.0.0.1/web/fr/8-plan-du-site.php">Plan du site</a></li>
<li><a href="http://127.0.0.1/web/fr/9-contact.php">Contact</a></li>
			</ul>
			<div class="spacer"></div>
		</div>
	</div>
<?php if (SYSTEM_DEBUG && STATS_DEBUG) {view_stat();}  ?>
</body>
</html>